services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwafpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - "3308"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - /home/tim/docker-volumes/jwafp-mysql-data:/var/lib/mysql
    networks:
      - jwafpnet

  api:
    build: ./api
    container_name: api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/jwafpdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CET
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - jwafpnet

  core:
    build: ./core
    container_name: core
    depends_on:
      - api
    environment:
      API_BASE_URL_INTERNAL: http://api:8081/api/v1/
      API_BASE_URL_PUBLIC: http://10.139.172.222:8081/api/v1/
    ports:
      - "8080:8080"
    networks:
      - jwafpnet

networks:
  jwafpnet:
    driver: bridge